# Generated by Django 3.0.3 on 2020-02-13 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='u_password',
            field=models.IntegerField(max_length=16),
        ),
    ]
