version: '3'

services:
  redis:
    image: redis:latest
    expose:
      - "6379"
  db:
    image: mysql:5.7
    ports:
      - '3308:3306'
    environment:
      MYSQL_DATABASE: 'cse312'
      MYSQL_ROOT_PASSWORD: 'change_me'
  web:
    build: .
    image: cse312
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/CSE312
    environment:
      - DEBUG=0
      - MYSQL_PASSWORD=change_me
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis


