version: '3'

services:
  redis:
    image: redis:latest
    expose:
      - "6379"
  db:
    image: mysql:5.7
    ports:
      - '3308:3306'
    environment:
      MYSQL_DATABASE: 'cse312'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: '123456789'
      MYSQL_ROOT_PASSWORD: '123456789'
  web:
    build: .
    command:
      python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/CSE312
    ports:
      - "8000:8000"
    links:
      - db
      - redis
